<?php
/**
 * Страница проекта в модуле "FAQ".
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 * @var iUmiHierarchyElement $project
 */

$project = $variables['page'];
?>

<div class="section_capt">
	<div class="container">
		<div class="row">
			<h1 umi:element-id="<?= $project->getId() ?>"
			    umi:field-name="h1"
			    umi:empty="<?= $this->translate('empty_page_name') ?>"
			>
				<?= $this->escape($project->getValue('h1')) ?>
			</h1>
		</div>

		<div class="row"
		     umi:element-id="<?= $project->getId() ?>"
		     umi:field-name="content"
		>
			<?= $project->getValue('content') ?>
		</div>
	</div>
</div>

<div>
	<?= $this->render($variables, 'faq/category/list') ?>
</div>
