<?php
/**
 * Поле типа "Дата".
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$field = $variables;
?>

<input
	type="date"
	name="<?= $field['input_name'] ?>"
	placeholder="<?= $this->escape($field['title']) ?>"
	<?= (isset($field['required']) ? ' required ' : '') ?>
	value="<?= isset($field['value']) ? $field['value'] : '' ?>"
/>

<span class="sub_text"><?= $this->escape($field['title']) ?></span>
