<?php
/**
 * Поле типа "Текст".
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$field = $variables;
?>

<textarea
	name="<?= $field['input_name'] ?>"
	placeholder="<?= $this->escape($field['title']) ?>"
	<?= isset($field['required']) ? ' required ' : '' ?>
><?= isset($field['value']) ? $this->escape($field['value']) : '' ?></textarea>

<span class="sub_text"><?= $this->escape($field['title']) ?></span>
