<?php
/**
 * Страница "Выбор способа оплаты".
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$paymentList = $variables['purchasing']['items'];
$submitUrl = $variables['purchasing']['submit_url'];
?>

<form id="payment_choose" method="post" action="<?= $submitUrl ?>">
	<div class="payment onestep del_row order_img_2">
		<div class="del_content">
			<h3 class="up input_capt">
				<?= $this->translate('payment_type') ?>
			</h3>

			<?= $this->render(["paymentList" => $paymentList], 'emarket/payment/choose/list') ?>
			<input type="submit" value="<?= $this->translate('continue') ?>">
		</div>
	</div>
</form>
