<?php
/**
 * Оплата по безналичному расчету.
 * @todo рефакторинг
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 * @var array $visibleFields
 */

$visibleFields = [
	'name' => $this->translate('organization_name'),
	'inn' => $this->translate('INN'),
	'kpp' => $this->translate('KPP'),
	'email' => $this->translate('legal_person_email'),
];
?>

<?php foreach ($visibleFields as $name => $title): ?>
	<?php foreach ($variables['form']['groups'] as $group): ?>
		<?php foreach ($group['fields'] as $field): ?>
			<?php if ($field['name'] === $name): ?>
				<?php
				if ($name === 'email') {
					$field['value'] = $variables['customerEmail'];
				}
				?>
				<div class="<?= $this->getFormFieldClass($field) ?>">
					<?= $this->render($field, "data/form_field/{$field['type']}") ?>
				</div>
			<?php endif; ?>
		<?php endforeach; ?>
	<?php endforeach; ?>
<?php endforeach; ?>
