<?php
/**
 * Способ оплаты "PayAnyWay".
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$data = $this->getPayAnyWayParams($variables);
?>

<form action="<?= $data['formAction'] ?>" method="post">
	<input type="hidden" name="MNT_ID" value="<?= $data['mntId'] ?>" />
	<input type="hidden" name="MNT_TRANSACTION_ID" value="<?= $data['mnTransactionId'] ?>" />
	<input type="hidden" name="MNT_CURRENCY_CODE" value="<?= $data['mntCurrencyCode'] ?>" />
	<input type="hidden" name="MNT_AMOUNT" value="<?= $data['mntAmount'] ?>" />
	<input type="hidden" name="MNT_TEST_MODE" value="<?= $data['mntTestMode'] ?>" />
	<input type="hidden" name="MNT_SIGNATURE" value="<?= $data['mntSignature'] ?>" />
	<input type="hidden" name="MNT_SUCCESS_URL" value="<?= $data['mntSuccessUrl'] ?>" />
	<input type="hidden" name="MNT_FAIL_URL" value="<?= $data['mntFailUrl'] ?>" />

	<div class="container grey_border">
		<?= $this->translate('payment_redirect_text') ?> PayAnyWay.
	</div>

	<div>
		<input type="submit" value="<?= $this->translate('pay') ?>" class="button big" />
	</div>
</form>

<script src="js/payment/send_form_immediately.js"></script>
