<?php
/**
 * Способ оплаты "Яндекс.Касса" версии 4.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */
?>

<div class="container grey_border">
	<?= $this->translate('payment_redirect_text') . ' Yandex.' ?>
</div>

<div>
	<a id="payUrl" href="<?= $variables['purchasing']['url'] ?>" class="button big" ><?= $this->translate('pay') ?></a>
</div>

<script src="js/payment/send_form_immediately.js"></script>