<?php
/**
 * Поле умных фильтров, которое нужно вывести с интервалом значений.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$dataType = $this->getFilterFieldAttribute($variables, 'data-type');
?>

<?php if ($dataType === 'date'): ?>
	<?= $this->render($variables, 'catalog/category/filters/field/interval/date') ?>
<?php else: ?>
	<?= $this->render($variables, 'catalog/category/filters/field/interval/slider') ?>
<?php endif; ?>
