<?php
/**
 * Блок оплаты заказа бонусами.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */
?>
<div id="spend_bonus_block">
	<div class="del_row">
		<div class="del_content">
			<h3 class="up input_capt">
				<?= $this->translate('spend_bonus') ?>
			</h3>
			<div>
				<div><?= $this->translate('available-bonus-short') ?> <span id="available_bonus"><?= $this->getAvailableBonus() ?></span></div>
				<p id="bonus_error"><?= $this->translate('bonus_wrong_value') ?></p>
				<div><input id="bonus" type="number" /></div>
				<button id="spend_bonus" type="button"><?= $this->translate('spend_bonus') ?></button>
			</div>
		</div>
	</div>
</div>