<?php
/**
 * Способ доставки ApiShip.
 * В шаблоне может быть выведен только один такой способ доставки.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

if ($this->getCommonVar('apiship_delivery_is_rendered')) {
	return;
}

$this->setCommonVar('apiship_delivery_is_rendered', true);
$delivery = $variables;
$disabledPaymentIdList = implode(',', $this->getDisabledPaymentIdList($delivery['id']));
?>

<div>
	<label>
		<input
			type="radio"
			data-api="api-ship"
			name="delivery-id"
			value="<?= $delivery['id'] ?>"
			data-disabledpayments="<?=$disabledPaymentIdList?>"
			required
			<?= $this->getRadioStatusByActivity($delivery) ?>
		/>

		<span></span>

		<p>
			<?= $this->escape($delivery['name']) ?>
		</p>
	</label>
</div>

<!--suppress JSUnusedLocalSymbols -->
<script>
	var ApiShipId = <?= $delivery['id'] ?>;
	var basketOrderId = <?= $this->getCommonVar('order_id') ?>;
</script>

<div id="order_delivery_apiship"></div>
<div id="apiShipWidget" class="apishipWidgetLoader">
	<img src="/templates/demomarket/img/preloader.gif" alt="waiting"/>
</div>

<link rel="stylesheet" href="/styles/common/css/jquery.mCustomScrollbar.css" />
<link type="text/css" rel="stylesheet" href="/styles/common/css/widget.Delivery.css" />

<script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&apikey=<?= $this->getYandexMapApiKeyByDeliveryId($delivery['id']) ?>" type="text/javascript"></script>
<script src="/styles/common/js/jquery.mCustomScrollbar.js" type="text/javascript"></script>
<script src="/styles/common/js/widget.Delivery.js" type="text/javascript"></script>
<script src="/templates/demomarket/js/apiship/initialize_widget.js" type="text/javascript"></script>
