<?php
/**
 * Превью новости в ленте.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 * @var iUmiHierarchyElement $newsItem
 */

$newsItem = $this->getPageById($variables['id']);
?>

<div class="news_box" umi:element-id="<?= $variables['id'] ?>" umi:region="row">
	<?= $this->render($newsItem, 'news/item/date') ?>

	<div class="news_text">
		<a href="<?= $variables['link'] ?>">
			<h4 umi:field-name="name" umi:delete="delete" umi:empty="<?= $this->translate('empty_page_name') ?>">
				<?= $this->escape($variables['header']) ?>
			</h4>
		</a>

		<div umi:field-name="anons" umi:empty="<?= $this->translate('empty_page_anons') ?>">
			<?= $newsItem->getValue('anons') ?>
		</div>

		<a href="<?= $variables['link'] ?>">
			<img src="img/blue_arrow.png" alt="blue_arrow">
		</a>
	</div>
</div>
