<?php
/**
 * Товарное наименование в корзине.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$product = $variables;
?>

<span class="text">
	<a href="<?= $this->getPath($product['page']) ?>">
		<?= $this->render($product, 'emarket/purchasing_one_step/cart/product/name') ?>
	</a>
</span>

<?= $this->render($product, 'emarket/purchasing_one_step/cart/product/total') ?>
