<?php
/**
 * Каталог лучших предложений.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

list($variables, $isShowNewItems) = $variables;
?>

<div id="bestItems" class="tab-pane fade in <?= $this->getActiveClass(!$isShowNewItems) ?>">
	<div class="row">
		<?php foreach ($this->getBestProducts() as $product): ?>
			<?= $this->render($product, 'catalog/product/preview/index') ?>
		<?php endforeach; ?>
	</div>
</div>
