<?php
/**
 * Страница блога.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 * @var iUmiHierarchyElement $blog
 */

$blog = $variables['page'];
?>

<div class="section_capt">
	<div class="container">
		<div class="row">
			<h1 umi:element-id="<?= $blog->getId() ?>"
			    umi:field-name="h1"
			    umi:empty="<?= $this->translate('empty_page_name') ?>"
			>
				<?= $this->escape($blog->getName()) ?>
			</h1>
		</div>
	</div>
</div>

<div class="blog">
	<div class="container">
		<?= $this->render($variables, 'blogs20/post/list') ?>
		<?= $this->render($variables, 'blogs20/post/new') ?>
	</div>
</div>
