<?php
/**
 * Блок для использования промокода.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */
$promoCodeSaved = $this->macros('emarket', 'getSavedPromoCode') != '';
?>
<div class="col-sm-12 col-lg-6 promocode">
	<?php if ($promoCodeSaved): ?>
		<?= $this->render($variables, 'emarket/cart/promocode/applied') ?>
	<?php else: ?>
		<?= $this->render($variables, 'emarket/cart/promocode/form') ?>
	<?php endif; ?>
</div>
