<?php
/**
 * Меню каталога товаров в подвале десктопной версии.
 * Разбито на две части - левую и правую.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 * @var array $categoryList
 */
$fullCategoryList = $this->getCommonVar('catalog_category_list');
$categoryId = $fullCategoryList['category_id'];
$categoryList = $this->filterCategoryList();
$categoryList = $this->sliceFooterMenuCategoryList($categoryList);
?>

<div class="list_products"
     umi:button-position="bottom left"
     umi:element-id="<?= $categoryId ?>"
     umi:region="list"
     umi:module="catalog"
     umi:sortable="sortable"
>
	<?php foreach ($this->getCategoryGroups($categoryList) as $group): ?>
		<div>
			<?php /** @var array $group */
			foreach ($group as $category): ?>
				<div class="category_list"
				     umi:element-id="<?= $category['id'] ?>"
				     umi:region="row"
				>
					<a href="<?= $category['link'] ?>">
						<h3 class="category_heading white_text"
						    umi:field-name="name"
						    umi:delete="delete"
						    umi:empty="<?= $this->translate('empty_section_name') ?>"
						>
							<?= $this->escape($category['text']) ?>
						</h3>
					</a>

					<?= $this->render($category, 'layout/footer/catalog_menu/sub_list') ?>
				</div>
			<?php endforeach; ?>
		</div>
	<?php endforeach; ?>
</div>
