<?php
/**
 * Меню главных страниц сайта в подвале.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var string $variables
 * @var array $pageList
 */

$menuId = $variables;
$data = $this->getMenu($menuId);
$pageList = $data['lines'];
?>

<?php if (umiCount($pageList) > 0): ?>
	<ul class="white_text">
		<?php foreach ($pageList as $page): ?>
			<li>
				<a href="<?= $page['link'] ?>">
					<?= $this->escape($page['name']) ?>
				</a>
			</li>
		<?php endforeach; ?>
	</ul>
<?php endif; ?>
