<?php
/**
 * Социальный блок в десктопной версии подвала сайта.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */
?>

<li>
	<a href="https://www.facebook.com/UMI.CMS/" target="_blank">
		<img src="img/social-fb.png" alt="">
	</a>
</li>

<li>
	<a href="https://vk.com/umi_cms" target="_blank">
		<img src="img/social-vk.png" alt="">
	</a>
</li>

<li>
	<a href="https://twitter.com/umi_cms" target="_blank">
		<img src="img/social-tw.png" alt="">
	</a>
</li>

<li>
	<a href="https://www.instagram.com/1c_umi/" target="_blank">
		<img src="img/social-in.png" alt="">
	</a>
</li>
