<?php
/**
 * Заголовок новости.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 * @var iUmiHierarchyElement $newsItem
 */

$newsItem = $variables['page'];
?>

<div class="section_capt">
	<div class="container">
		<div class="row">
			<?= $this->render($variables, 'layout/header/breadcrumbs') ?>

			<h1 umi:element-id="<?= $variables['pageId'] ?>" umi:field-name="h1"
				umi:empty="<?= $this->translate('empty_page_name') ?>">
				<?= $this->escape($newsItem->getValue('h1')) ?>
			</h1>
		</div>
	</div>
</div>
