<?php
/**
 * Дата новости.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 * @var iUmiHierarchyElement $newsItem
 */

$newsItem = $variables;
?>

<div class="news_date">
	<div><?= $this->getPublishDay($newsItem) ?></div>

	<div class="up">
		<p><?= $this->getPublishMonth($newsItem) ?></p>
		<p><?= $this->getPublishYear($newsItem) ?></p>
	</div>
</div>
