<?php
/**
 * Системная страница результата отправки запроса на восстановление пароля.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */
?>

<div class="section_capt">
	<div class="container">
		<div class="row">
			<h1><?= $this->escape($variables['header']) ?></h1>
		</div>
	</div>
</div>

<div class="container grey_border">
	<p><?= $this->getPasswordForgetDoMessage($variables) ?></p>
</div>
