<?php
/**
 * Системная страница результата входа на сайт.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$result = $this->macros('users', 'login_do');
$template = (isset($result['user_id'])) ? 'success' : 'failure';
?>

<div class="section_capt">
	<div class="container">
		<div class="row">
			<h1><?= $this->escape($variables['header']) ?></h1>
		</div>
	</div>
</div>

<div class="container grey_border">
	<?= $this->render($result, "users/login_do/{$template}") ?>
</div>
