<?php
/**
 * Страница фотографии.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 * @var iUmiHierarchyElement $page
 */

$page = $variables['page'];
$pageId = $page->getId();
?>

<div class="section_capt">
	<div class="container">
		<div class="row">
			<?= $this->render($variables, 'layout/header/breadcrumbs') ?>
		</div>
	</div>
</div>

<div class="container">
	<div class="one_photo">
		<?= $this->render(
			[
				'id' => $pageId,
				'fieldName' => 'photo',
				'src' => $page->getValue('photo'),
				'alt' => $this->getPhotoAlt($page),
				'title' => $this->getPhotoTitle($page),
				'empty' => $this->getNoPhotoPath(),
				'width' => 495,
				'objectId' => $page->getObjectId(),
				'folderHash' => $this->getPhotoDirHash($photo),
				'fileHash' => $this->getPhotoPathHash($photo),
			],
			'library/thumbnail'
		) ?>

		<div class="title">
			<h4 umi:element-id="<?= $pageId ?>"
			    umi:field-name="h1"
			    umi:empty="<?= $this->translate('empty_page_name') ?>"
			>
				<?= $this->escape($page->getValue('h1')) ?>
			</h4>

			<div class="gray_text"
			     umi:element-id="<?= $pageId ?>"
			     umi:field-name="descr"
			     umi:empty="<?= $this->translate('empty_page_description') ?>"
			>
				<p><?= $page->getValue('descr') ?></p>
			</div>
		</div>
	</div>
</div>
