<?php
/**
 * Кнопка "Добавить к сравнению".
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var iUmiHierarchyElement $variables
 */

$product = $variables;
?>

<div class="col-md-6 col-lg-3 rew diff">
	<a href="<?= $this->getProductComparisonLink($product) ?>">
		<i class="sprite-item sprite-item_icons_circle_blue inline"></i>
		<?= $this->getComparisonMessage($product) ?>
	</a>
</div>
