<?php
/**
 * Кнопка "Добавить к сравнению".
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var iUmiHierarchyElement $variables
 */

$product = $variables;
$data = $this->macros('emarket', 'getCompareLink', [$product->getId()]);
?>

<div class="col-md-6 col-lg-3 rew diff">
	<a href="<?= $this->getProductComparisonLink($data) ?>">
		<i class="sprite-item sprite-item_icons_circle_blue inline"></i>
		<?= $this->getComparisonMessage($data) ?>
	</a>
</div>
