<?php
/**
* Статический блок с товарами в корзине (не поддерживается изменение содержимого корзины).
*
* @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
* @var array $variables
*/

$cart = $this->macros('emarket', 'cart');
?>

<div class="order_bill">
	<div id="billForm">
		<div class="del_row">
			<div class="del_content">
				<h3><?= $this->getOrderItemCountMessage($cart) ?></h3>
				<?= $this->render($cart, 'emarket/purchasing_one_step/cart/product_list') ?>
				<?= $this->render($cart, 'emarket/purchasing_one_step/cart/result') ?>
			</div>
		</div>
	</div>
</div>

