<?php
/**
 * Все всплывающие окна на сайте (скрыты по умолчанию)
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */
?>

<?php if ($this->isPushNotificationModuleExists()) : ?>
	<?= $this->render($variables, 'layout/modal/push') ?>
<?php endif; ?>

<?= $this->renderWebform($this->getCallbackId(), 'layout/modal/callback') ?>

<?= $this->render($variables, 'layout/modal/buy') ?>
<?= $this->render($variables, 'layout/modal/buy_one_click') ?>

<?php if($variables['user']['type'] === 'guest'): ?>
	<?= $this->render($variables, 'layout/modal/login') ?>
<?php endif; ?>
