<?php
/**
 * Форма умных фильтров в мобильной версии.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$filters = $this->getCommonVar('smart_filters');
$fieldList = $this->getFilterFields($filters);
?>

<?php if (umiCount($fieldList) > 0): ?>
	<div class="filter_mobile hidden-lg hidden-md">
		<div class="sidebar">
			<div class="row">
				<form class="productForm mobile_filters" data-category="<?= $filters['category-id'] ?>">
					<?php foreach ($fieldList as $field): ?>
						<?= $this->render($field, 'catalog/category/filters/field') ?>
					<?php endforeach; ?>

					<div class="col-md-12">
						<input type="submit" value="<?= $this->translate('apply') ?>" class="show_result" />
						<input type="reset" value="<?= $this->translate('reset') ?>" class="reset" />
					</div>
				</form>
			</div>
		</div>
	</div>
<?php endif; ?>
