<?php
/**
 * Опция поля умных фильтров, которое нужно вывести с чекбоксом.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$data = $this->getCheckboxFilterFieldData($variables);
?>

<div>
	<label>
		<input type="checkbox" name="<?= $data['name'] ?>" id="<?= $data['id'] ?>" value="<?= $data['value'] ?>" />
		<span></span>
		<?= $data['value'] ?>
	</label>
</div>
