<?php
/**
 * Список способов оплаты.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$paymentList = isset($variables["paymentList"]) ? $variables["paymentList"] : [];
$isOneStep = isset($variables["isOneStep"]) ? $variables["isOneStep"] : false;
?>

<?php foreach ($paymentList as $payment): ?>
	<div class="choose-payment">
		<label class="<?= $this->getRadioStatusByActivity($payment) ? 'checked' : '' ?>">
			<input
				type="radio"
				name="payment-id"
				class="<?= $payment['type-name'] ?>"
				value="<?= $payment['id'] ?>"
				required
				<?= $this->getRadioStatusByActivity($payment) ?>
			/>

			<?php if ($isOneStep): ?>
				<img src="img/payments/<?= $this->escape($payment['type-name']) ?>.png"/>
				<span><?= $this->escape($payment['name']) ?></span>
			<?php else: ?>
				<span></span>
				<?= $this->escape($payment['name']) ?>
			<?php endif; ?>
		</label>
	</div>
<?php endforeach; ?>
