<?php
/**
 * Выбор адреса доставки (может включать способы доставки с типом "Самовывоз").
 * Форма создания нового адреса доставки.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 * @var bool $isRenderSaveButton
 */

$isRenderSaveButton = isset($variables['isRenderSaveButton']) && $variables['isRenderSaveButton'];
$selfDeliveryList = $this->getSelfDeliveryList($variables);
?>

<div class="delivery_address onestep del_row order_img_1">
	<div class="del_content">
		<h3 class="up input_capt">
			<?php if (isEmptyArray($selfDeliveryList)): ?>
				<?= $this->translate('choose_delivery_address') ?>
			<?php else: ?>
				<?= $this->translate('choose-delivery-address-and-self-delivery') ?>
			<?php endif; ?>
		</h3>

		<input type="hidden" name="delivery-address" value="new" />

		<?php foreach ($this->getSelfDeliveryList($variables) as $delivery): ?>
			<?= $this->render($delivery, 'emarket/delivery/address/self_delivery') ?>
		<?php endforeach; ?>

		<?php foreach ($this->getAddressList($variables) as $address): ?>
			<?= $this->render($address, 'emarket/delivery/address/item') ?>
		<?php endforeach; ?>

		<?php if ($this->canShowNewDeliveryAddressOption($variables)): ?>
			<div>
				<label>
					<input type="radio" name="delivery-address" value="new" />
					<span></span>
					<p>
						<?= $this->translate('new_delivery_address') ?>
					</p>
				</label>
			</div>
		<?php endif; ?>
	</div>

	<?php if ($this->canShowNewDeliveryAddressForm($variables)): ?>
		<div class="del_content">
			<div id="new-address">
				<?= $this->render(['form' => $this->getCreateForm($variables['type-id']), 'displayHeader' => false], 'data/form') ?>
				<?php if ($isRenderSaveButton): ?>
					<div class="del_content">
						<input id="save-delivery" type="submit" value="<?= $this->translate('confirm-address') ?>">
					</div>
				<?php endif; ?>
			</div>
		</div>

		<script id="add_address_template" type="text/template">
			<div class="form_element">
				<label>
					<input type="radio" name="delivery-address" value="<%= addressId %>" required checked="checked">
					<span></span>
					<p><%= address.join(', ') %></p>
				</label>
			</div>
		</script>
	<?php endif; ?>
</div>
