<?php
/**
 * Конференция форума.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 * @var umiHierarchyElement $conference
 */

$conference = $variables['page'];
$newTopic = $this->getNewTopic($conference->getId());
?>

<div class="section_capt">
	<div class="container">
		<div class="row">
			<h1 umi:element-id="<?= $conference->getId() ?>"
			    umi:field-name="h1"
			    umi:empty="<?= $this->translate('empty_page_name') ?>"
			>
				<?= $this->escape($conference->getValue('h1')) ?>
			</h1>
		</div>

		<div class="row"
		     umi:element-id="<?= $conference->getId() ?>"
		     umi:field-name="descr"
		>
			<?= $conference->getValue('descr') ?>
		</div>
	</div>
</div>

<?= $this->render($variables, 'forum/topic/list') ?>

<div class="container">
	<div class="comment">
		<div class="comment_add">
			<?php if ($this->canAddNewForumTopic($newTopic)): ?>
				<?= $this->render($newTopic, 'forum/topic/new') ?>
			<?php else: ?>
				<p><?= $this->translate('login_to_add_new_forum_topic') ?></p>
			<?php endif; ?>
		</div>
	</div>
</div>
