<?php
/**
 * Страница сообщения в топике форума.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 * @var iUmiHierarchyElement $message
 */

$message = $variables['page'];
$topic = end($variables['parents']);
?>

<div class="section_capt">
	<div class="container">
		<div class="row">
			<?= $this->render($variables, 'layout/header/breadcrumbs') ?>

			<h1 umi:element-id="<?= $variables['pageId'] ?>"
				umi:field-name="h1"
				umi:empty="<?= $this->translate('empty_page_name') ?>"
			>
				<?= $this->escape($variables['header']) ?>
			</h1>
		</div>
	</div>
</div>

<div class="container">
	<div class="comment page_with_comment">
		<div class="comment_list">
			<div class="one_comment" umi:element-id="<?= $variables['pageId'] ?>">
				<div class="date"
					 umi:field-name="publish_time"
					 umi:empty="<?= $this->translate('empty_publish_time') ?>"
				>
					<?= $this->getFormattedPublishTime($message) ?>
				</div>

				<div class="name">
					<?= $this->getFullAuthorName($message->getValue('author_id')) ?>
				</div>

				<div class="text"
					 umi:field-name="message"
					 umi:delete="delete"
					 umi:empty="<?= $this->translate('empty') ?>"
				>
					<?= $this->escape($message->getValue('message')) ?>
				</div>
			</div>

			<a href="<?= $this->getPath($topic) ?>">
				<?= $this->translate('back_to_parent_topic') ?>
			</a>
		</div>
	</div>
</div>
