<?php
/**
 * Блок из трех вариантов отображения превью товаров каталога (только в десктопной версии):
 *   - Плитка
 *   - Список с картинками
 *   - Список без картинок
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */
?>

<div class="sort_btn float_right hidden-xs hidden-sm">
	<a data-class="goods">
		<i class="sprite-sort sprite-lg_blue"></i>
	</a>

	<a data-class="catalog_list">
		<i class="sprite-sort sprite-sm_gray"></i>
	</a>

	<a data-class="catalog_inline">
		<i class="sprite-sort sprite-xs_gray"></i>
	</a>
</div>
